name:                note-fs
version:             0.1.0.0
github:              bogo8liuk/note-fs
license:             GPL-3
author:              Luca Borghi
copyright:           "2023 Luca Borghi"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bogo8liuk/note-fs#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- text
- mtl
- containers
- filepath
- directory
- process
- optparse-applicative
- hs-utils

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unused-do-bind

library:
  source-dirs: src

executables:
  nfs-repl:
    main:                Repl.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Repl
    dependencies:
    - note-fs
  nfs-see:
    main:                See.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is See
    dependencies:
    - note-fs
  nfs-take:
    main:                Take.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Take
    dependencies:
    - note-fs

tests:
  note-fs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - note-fs
